const simplified = {
  title: "通知设置",
  subtitle: "管理 NURI 的提醒，以及这台 iPhone 上的测试通知。",
  permission: "系统通知权限",
  authorized: "已允许",
  provisional: "已暂时允许",
  denied: "已关闭",
  notDetermined: "尚未请求",
  unknown: "暂时无法读取",
  allow: "允许通知",
  systemSettings: "打开系统通知设置",
  remoteTitle: "每日精选与关怀提醒",
  remoteDescription: "这是账户级偏好，也会影响同账号的旧版 NURI。此应用的远程推送仍需后端支持对应的 App 身份；保存偏好不代表推送已接通。本机测试间隔不会改变后端发送频率。",
  remoteToggle: "接收每日精选与关怀提醒",
  remoteUnavailable: "账户通知偏好暂时无法读取。请登录后重试；这不会影响本机测试提醒。",
  remoteSaved: "NURI 推送偏好已保存。",
  remoteFailed: "推送偏好未保存，请检查网络后重试。",
  localTitle: "本机测试提醒",
  localBadge: "仅用于测试",
  localDescription: "按你填写的间隔在这台 iPhone 上显示测试通知。不会触发 AI 回复，也不会修改 NURI 的真实推送频率。",
  localToggle: "启用本机测试提醒",
  interval: "提醒间隔",
  minutes: "分钟",
  seconds: "秒",
  intervalHint: "分钟和秒可自由填写，总时长须为 1 秒至 365 天。秒数超过 59 会自动换算。",
  save: "保存测试提醒",
  saving: "正在保存…",
  dirty: "修改尚未保存",
  running: "本机测试提醒已安排。",
  stopped: "本机测试提醒已关闭。",
  notScheduled: "设置已记录，但目前没有安排通知。请允许系统通知后再保存。",
  limited: "短间隔采用有限批次：已安排 {count} 条，覆盖约 {seconds} 秒。批次完成后，可回来重新保存测试。",
  repeating: "已安排重复提醒：每 {minutes} 分 {seconds} 秒一次。",
  localUnavailable: "本机通知功能暂时无法读取，请重试。",
  localFailed: "测试提醒未保存，请重试。",
  permissionFailed: "暂时无法请求通知权限，请尝试打开系统设置。",
  settingsFailed: "暂时无法打开系统设置。",
  invalidInteger: "请填写非负整数的分钟和秒数。",
  invalidZero: "提醒间隔须至少为 1 秒。",
  invalidRange: "提醒间隔不能超过 365 天。",
  retry: "重新读取",
  loading: "正在读取通知设置…",
} as const;

export type NotificationCopyKey = keyof typeof simplified;

const english: Record<NotificationCopyKey, string> = {
  title: "Notification settings",
  subtitle: "Manage NURI reminders and test notifications on this iPhone.",
  permission: "System notification permission",
  authorized: "Allowed",
  provisional: "Provisionally allowed",
  denied: "Turned off",
  notDetermined: "Not requested yet",
  unknown: "Unavailable",
  allow: "Allow notifications",
  systemSettings: "Open system notification settings",
  remoteTitle: "Daily selections and care reminders",
  remoteDescription: "This account preference also affects the original NURI app using the same account. Remote push for this app still requires backend support for its app identity; saving a preference does not connect delivery. Local test intervals do not change the backend schedule.",
  remoteToggle: "Receive daily selections and care reminders",
  remoteUnavailable: "Account preferences could not be loaded. Sign in and retry; local test reminders still work.",
  remoteSaved: "NURI notification preference saved.",
  remoteFailed: "The preference was not saved. Check your connection and retry.",
  localTitle: "Local test reminders",
  localBadge: "For testing only",
  localDescription: "Show test notifications on this iPhone at your chosen interval. This does not generate AI replies or change NURI's real notification frequency.",
  localToggle: "Enable local test reminders",
  interval: "Reminder interval",
  minutes: "Minutes",
  seconds: "Seconds",
  intervalHint: "Enter any minutes and seconds, from 1 second to 365 days in total. Seconds above 59 are converted automatically.",
  save: "Save test reminders",
  saving: "Saving…",
  dirty: "Changes have not been saved",
  running: "Local test reminders scheduled.",
  stopped: "Local test reminders turned off.",
  notScheduled: "Settings were recorded, but no notifications are scheduled. Allow system notifications and save again.",
  limited: "Short intervals use a finite batch: {count} notifications, covering about {seconds} seconds. Return and save again after this batch finishes.",
  repeating: "Repeating reminder scheduled every {minutes} min {seconds} sec.",
  localUnavailable: "Local notification settings could not be loaded. Please retry.",
  localFailed: "Test reminders were not saved. Please retry.",
  permissionFailed: "Notification permission could not be requested. Try system settings.",
  settingsFailed: "System settings could not be opened.",
  invalidInteger: "Enter non-negative whole numbers for minutes and seconds.",
  invalidZero: "The interval must be at least 1 second.",
  invalidRange: "The interval cannot exceed 365 days.",
  retry: "Reload settings",
  loading: "Loading notification settings…",
};

const traditional: Record<NotificationCopyKey, string> = {
  title: "通知設定",
  subtitle: "管理 NURI 的提醒，以及這台 iPhone 上的測試通知。",
  permission: "系統通知權限",
  authorized: "已允許",
  provisional: "已暫時允許",
  denied: "已關閉",
  notDetermined: "尚未請求",
  unknown: "暫時無法讀取",
  allow: "允許通知",
  systemSettings: "開啟系統通知設定",
  remoteTitle: "每日精選與關懷提醒",
  remoteDescription: "這是帳號級偏好，也會影響同帳號的舊版 NURI。此應用程式的遠端推播仍需後端支援對應的 App 身分；儲存偏好不代表推播已接通。本機測試間隔不會改變後端發送頻率。",
  remoteToggle: "接收每日精選與關懷提醒",
  remoteUnavailable: "帳號通知偏好暫時無法讀取。請登入後重試；這不會影響本機測試提醒。",
  remoteSaved: "NURI 推播偏好已儲存。",
  remoteFailed: "推播偏好未儲存，請檢查網路後重試。",
  localTitle: "本機測試提醒",
  localBadge: "僅供測試",
  localDescription: "按你填寫的間隔在這台 iPhone 上顯示測試通知。不會觸發 AI 回覆，也不會修改 NURI 的真實推播頻率。",
  localToggle: "啟用本機測試提醒",
  interval: "提醒間隔",
  minutes: "分鐘",
  seconds: "秒",
  intervalHint: "分鐘和秒可自由填寫，總時長須為 1 秒至 365 天。秒數超過 59 會自動換算。",
  save: "儲存測試提醒",
  saving: "正在儲存…",
  dirty: "修改尚未儲存",
  running: "本機測試提醒已安排。",
  stopped: "本機測試提醒已關閉。",
  notScheduled: "設定已記錄，但目前沒有安排通知。請允許系統通知後再儲存。",
  limited: "短間隔採用有限批次：已安排 {count} 則，涵蓋約 {seconds} 秒。批次完成後，可回來重新儲存測試。",
  repeating: "已安排重複提醒：每 {minutes} 分 {seconds} 秒一次。",
  localUnavailable: "本機通知功能暫時無法讀取，請重試。",
  localFailed: "測試提醒未儲存，請重試。",
  permissionFailed: "暫時無法請求通知權限，請嘗試開啟系統設定。",
  settingsFailed: "暫時無法開啟系統設定。",
  invalidInteger: "請填寫非負整數的分鐘和秒數。",
  invalidZero: "提醒間隔須至少為 1 秒。",
  invalidRange: "提醒間隔不能超過 365 天。",
  retry: "重新讀取",
  loading: "正在讀取通知設定…",
};

export function notificationText(
  locale: string,
  key: NotificationCopyKey,
  values: Record<string, string | number> = {},
): string {
  const copy = locale === "en" ? english : locale === "zh-TW" ? traditional : simplified;
  return copy[key].replace(/\{(\w+)\}/g, (token, name) => name in values ? String(values[name]) : token);
}
