import type { Locale } from "./i18n";

const en = {
  title: "Third-party AI permission",
  intro: "NURI uses OpenAI, a third-party AI provider, to generate replies, an initial chat greeting, personalised suggestions and recommendations, and to transcribe voice recordings.",
  data: "If you allow AI, relevant family profile details (such as names, birth dates, location, parenting concerns and health notes), conversations, tasks/reflections, selected images and recorded audio may be sent through NURI to OpenAI. Audio is sent for transcription; images may contain faces or other private details. Share only what is needed.",
  provider: "OpenAI publicly states that API data is not used for model training by default unless customers opt in. Retention depends on the API and service settings; this is not a promise of zero retention.",
  separate: "This permission applies only to this account on this device in Native Lab, for the notice version shown below. It is separate from history/training, external research and notification preferences. Registration or a previous app login does not grant permission.",
  withdraw: "You can withdraw at any time. Withdrawal blocks new related requests from this lab app immediately; requests already sent may still finish. It does not automatically delete uploaded history or shared cloud data, or stop processing by the original app or server background jobs. You can manage cloud preferences, clear cloud data or request account deletion in Profile.",
  denied: "AI is not allowed. Sign-in, existing non-AI records, privacy settings and account deletion remain available. Family profile uploads, AI chat and personalised generation stay blocked.",
  allowed: "AI permission is enabled for this account and notice version.",
  loading: "Checking account and saved permission…",
  signedOut: "Sign in to choose permission for your own account. No AI permission is assumed.",
  loadError: "Permission could not be verified. AI requests remain blocked. Please retry.",
  storageError: "Your choice could not be fully saved. AI is blocked in this running app; please retry before restarting. Do not assume withdrawal has been durably saved.",
  changed: "The account or permission changed. No choice was applied to the new account. Check again.",
  linkError: "The link could not be opened. Please retry.",
  privacy: "NURI privacy policy",
  processing: "OpenAI API data-processing statement",
  allow: "Allow sending relevant information to OpenAI for AI features",
  decline: "Do not allow",
  revoke: "Withdraw AI permission",
  retry: "Check again",
  nonAI: "Continue to Profile and non-AI features",
  login: "Sign in",
  version: "Notice version",
  header: "AI permission",
  banner: "AI requests are blocked. Review permission to use AI; non-AI features remain available.",
};
const zhCN: typeof en = {
  title: "第三方 AI 使用许可",
  intro: "NURI 使用第三方 AI 服务商 OpenAI 生成回复、新对话的自动问候、个性化建议和推荐，并将录音转成文字。",
  data: "允许后，相关家庭资料（例如姓名、出生日期、居住地、育儿困扰与健康备注）、对话、任务／反思、主动选择的图片与录制的音频可能经由 NURI 发送给 OpenAI。录音用于转录；图片可能包含人脸或其他隐私信息。请仅提供必要信息。",
  provider: "OpenAI 公开说明：API 数据默认不用于模型训练，除非客户主动选择共享。留存取决于接口与服务设置；这不代表零留存承诺。",
  separate: "本许可仅适用于本设备 Native Lab 中的当前账号和下方告知版本。它独立于历史／训练、外部研究与通知偏好；注册或曾在原版登录不代表已许可。",
  withdraw: "你可随时撤回。撤回会立即阻止本实验版新的相关请求；已发送的请求仍可能继续完成。撤回不会自动删除已上传历史或共享云数据，也不能停止原版 App 或服务器后台任务的处理。你可在个人资料中管理云端偏好、清除云数据或申请删除账号。",
  denied: "目前未允许 AI。登录、已有非 AI 记录、隐私设置与删除账号仍可使用；家庭资料上传、AI 对话及个性化生成保持阻止。",
  allowed: "当前账号已允许此告知版本的 AI 使用。",
  loading: "正在核对账号与已保存许可…",
  signedOut: "请登录后为自己的账号选择许可。不会默认视为允许 AI。",
  loadError: "无法确认许可，AI 请求仍被阻止。请重试。",
  storageError: "选择尚未完整保存。本次运行中的 AI 已被阻止，请在重启前重试；不要假定撤回已持久保存。",
  changed: "账号或许可已变更，未将本次选择应用到新账号。请重新核对。",
  linkError: "无法打开链接，请重试。",
  privacy: "NURI 隐私政策",
  processing: "OpenAI API 数据处理声明",
  allow: "允许将相关信息发送给 OpenAI 以使用 AI 功能",
  decline: "暂不允许",
  revoke: "撤回 AI 使用许可",
  retry: "重新核对",
  nonAI: "继续使用个人资料与非 AI 功能",
  login: "登录",
  version: "告知版本",
  header: "AI 使用许可",
  banner: "AI 请求已阻止。使用 AI 前请查看许可；非 AI 功能仍可使用。",
};
const zhTW: typeof en = {
  title: "第三方 AI 使用許可",
  intro: "NURI 使用第三方 AI 服務商 OpenAI 產生回覆、新對話的自動問候、個人化建議和推薦，並將錄音轉成文字。",
  data: "允許後，相關家庭資料（例如姓名、出生日期、居住地、育兒困擾與健康備註）、對話、任務／反思、主動選擇的圖片與錄製的音訊可能經由 NURI 傳送給 OpenAI。錄音用於轉錄；圖片可能包含人臉或其他隱私資訊。請僅提供必要資訊。",
  provider: "OpenAI 公開說明：API 資料預設不用於模型訓練，除非客戶主動選擇分享。保留時間取決於介面與服務設定；這不代表零保留承諾。",
  separate: "本許可僅適用於本裝置 Native Lab 中的目前帳號和下方告知版本。它獨立於歷史／訓練、外部研究與通知偏好；註冊或曾在原版登入不代表已許可。",
  withdraw: "你可隨時撤回。撤回會立即阻止本實驗版新的相關請求；已傳送的請求仍可能繼續完成。撤回不會自動刪除已上傳歷史或共享雲端資料，也不能停止原版 App 或伺服器背景工作的處理。你可在個人資料中管理雲端偏好、清除雲端資料或申請刪除帳號。",
  denied: "目前未允許 AI。登入、既有非 AI 記錄、隱私設定與刪除帳號仍可使用；家庭資料上傳、AI 對話及個人化產生保持阻止。",
  allowed: "目前帳號已允許此告知版本的 AI 使用。",
  loading: "正在核對帳號與已儲存許可…",
  signedOut: "請登入後為自己的帳號選擇許可。不會預設視為允許 AI。",
  loadError: "無法確認許可，AI 請求仍被阻止。請重試。",
  storageError: "選擇尚未完整儲存。本次執行中的 AI 已被阻止，請在重新啟動前重試；不要假定撤回已持久儲存。",
  changed: "帳號或許可已變更，未將本次選擇套用到新帳號。請重新核對。",
  linkError: "無法開啟連結，請重試。",
  privacy: "NURI 隱私政策",
  processing: "OpenAI API 資料處理聲明",
  allow: "允許將相關資訊傳送給 OpenAI 以使用 AI 功能",
  decline: "暫不允許",
  revoke: "撤回 AI 使用許可",
  retry: "重新核對",
  nonAI: "繼續使用個人資料與非 AI 功能",
  login: "登入",
  version: "告知版本",
  header: "AI 使用許可",
  banner: "AI 請求已阻止。使用 AI 前請查看許可；非 AI 功能仍可使用。",
};
export function aiConsentCopy(locale: Locale) { return locale === "en" ? en : locale === "zh-TW" ? zhTW : zhCN; }
